# Generated by Django 4.1.6 on 2023-03-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
                ('u_email', models.EmailField(max_length=20)),
            ],
        ),
    ]
