# Generated by Django 4.1.6 on 2023-03-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarHome', '0003_rename_u_name_login_u_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='u_id',
            field=models.IntegerField(default=100),
        ),
    ]
