# Generated by Django 4.1.6 on 2023-03-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarHome', '0004_login_u_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='userAcc',
        ),
    ]
