# Generated by Django 4.1.6 on 2023-03-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarHome', '0005_rename_login_useracc'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracc',
            name='u_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
